version: "3"
services:
  node:
    env_file:
        - .env
    image: node:16-alpine3.11
    container_name: community_platform_node
    working_dir: /home/node/app
    volumes:
      - ./app:/home/node/app
      - ./node.sh:/home/node/node.sh
    command: npm run ${ENVIRONMENT}
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      ENVIRONMENT: ${ENVIRONMENT}
      BASE_URL: ${BASE_URL}
    ports:
      - ${PORT_API}:5000
    links:
      - database
    networks:
      - nodenetwork

  database:
    image: postgres
    container_name: community_platform_db
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    expose:
      - 5432
    ports:
      - ${PORT_DATABASE}:5432
    networks:
      - nodenetwork
  
  adminer:
    image: adminer
    container_name: community_platform_adminer
    restart: always
    ports:
      - ${PORT_ADMINER}:8080
    links:
      - database
    networks:
      - nodenetwork

networks: 
  nodenetwork:
    driver: bridge
    external:
      name: external-node